### ISSUE TITLE
Problem when running locally

### ISSUE THREAD

**Issue by Toutouwai** [pospi/imthumb#5]
imthumb works great on my remote server, but when I try to run it locally I get the error:
Undefined variable: handler in imthumb-requesthandler.class.php on line 170
I'm using EasyPHP with PHP v5.3.8 and ImageMagick is installed. I expect the error is due to something about my local environment - does imthumb need any particular PHP extensions loaded besides ImageMagick?

**Comment by pospi** [comment]
Interesting that that was working actually, there was a problem with the way the scoping of the image handler was handled in that method.
Fixed in e44f312, and I've tagged v2.0 as well for good measure as it turns out I haven't done that yet!

**Comment by Toutouwai** [comment]
Hi, thanks for looking at this issue.
With the updated version I get...
Notice: Array to string conversion in imthumb-cache.class.php on line 231
Fatal error: Uncaught exception 'ImThumbException' with message 'Could not set image headers, output already started' in imthumb-http.class.php on line 35

Any suggestions?

**Comment by pospi** [comment]
Hmm that's a weird one, from looking at the code it might be a configuration issue? Are your configuration vars for `baseDir`, `cachePrefix`, `cacheSalt` & `cacheSuffix` all strings?

You could also avoid the error by disabling notices (the fatal error is only thrown because the notice is output), but finding the actual underlying problem would be much better of course...

**Comment by Toutouwai** [comment]
The error notice occurs with the default settings (i.e. when there is no timthumb-config.php file present - this file is optional, right?).

Turning off error notices does indeed allow the image to be rendered. Error notices are off on the remote server so perhaps that's why I haven't struck this issue until I tried running imthumb locally.

**Comment by Toutouwai** [comment]
The readme links to the TimThumb documentation for the config file, but I don't see mention of the baseDir and cacheSalt variables there. Do those variables need to be explicitly defined? Thanks.

**Comment by Toutouwai** [comment]
return $cacheDir . '/' . $this->cachePrefix . md5($this->cacheSalt . implode('', $imageHandle->params()) . ImThumb::VERSION) . $this->cacheSuffix;
In `$imageHandle->params()`, `sourceHandlers` is itself an array.

**Comment by pospi** [comment]
Ahh that makes sense. Thanks for digging in a bit!
If we switch `implode()` out for `json_encode()` does it work? That might
be the easiest way, may have to define some serializable interfaces on some
classes though.

If we can make it happen that way I'm happy to merge a PR for you,
otherwise I'll take a look through the other objects that can be stored in
the image handler params when I have time (:

**Comment by Toutouwai** [comment]
`json_encode()` sounds like it should work. Or otherwise something to strip out the second level of the `$imageHandle->params()` array, like...
    array_filter($imageHandle->params(), 'is_scalar')
...or a function to recursively implode the multidimensional array.

However, none of these seem to work when error reporting is set to E_ALL - I get a not very helpful 
    The image "..." cannot be displayed because it contains errors
message which makes it hard to debug further.

**Comment by pospi** [comment]
Do you get anything in the HTTP headers? From memory (it's going back a way
now) the library will output any errors it catches there so you can still
view them even if it successfully sent a `Content-Type` header. You might
also be able to see what's coming out if you try to open the image in a
text editor- you should see any error output from PHP above the binary
image data.

**Comment by Toutouwai** [comment]
I don't see any errors output in the headers, but I did find the following in the Apache error log:

     PHP Strict Standards:  Non-static method Imagick::getversion() should not be called statically, assuming $this from incompatible context in imthumb-http.class.php on line 73
