### ISSUE TITLE
Error with PHP Strict Standards

### ISSUE THREAD

**Issue by Toutouwai** [pospi/imthumb#6]
I thought it best to move this to a new issue...

     PHP Strict Standards:  Non-static method Imagick::getversion() should not be called statically, assuming $this from incompatible context in imthumb-http.class.php on line 73

Meeting strict standard requirements becomes more of an issue as hosting providers upgrade the installed version of PHP. `E_STRICT` is not included in `E_ALL` up to PHP 5.3, but is included in `E_ALL` for PHP 5.4 and newer. `display_errors` also defaults to on, which means that imthumb doesn't work out-of-the-box for recent versions of PHP.

I've just had a situation where a shared host upgraded to PHP 5.4, causing imthumb to break across a number of my client websites.

**Comment by Toutouwai** [comment]
Think all that's needed to fix this error is to change...

    $imVer = Imagick::getVersion();

...to...

    $im = new Imagick();
    $imVer = $im->getVersion();

This should be submitted as a pull request, I know, but I'm a Github newbie and I haven't learned how yet. Will submit it properly when I have time.

**Comment by pospi** [comment]
no worries I had time today, that should do it (:
